[options]
db_host = localhost
db_port = 5432
db_user = odoo
db_password = admin
http_port = 8069
admin_passwd = $pbkdf2-sha512$25000$jpFSKqUUghCCMEZIiRFC6A$DVsNOIP3Zr9LToSU84fU8OJl2OZgFGH67tnhrY/7KCPE7NEsZhkDd37h6AuIyN7IKpCUC/nWwteVj5Veg8ap2g
addons_path = F:\Odoo16\custom_module,F:\Odoo16\odoo\addons

